import { db } from "@/db";
import {
  chapters,
  categories,
  members,
  users,
  posts,
  post_comments,
  post_likes,
  announcements,
  events,
  event_attendance,
  visitors,
  referrals,
  business_transactions,
  organization_settings,
  notifications,
  activity_log,
  membership_plans,
  payments,
  trainings,
  training_attendance,
} from "@/db/schema";
import { sql } from "drizzle-orm";

export async function ensureSeeded() {
  try {
    const existingOrg = await db.select().from(organization_settings).limit(1);
    if (existingOrg.length > 0) {
      return;
    }

    console.log("Seeding Membership Business Network database...");

    // 1. Organization Settings
    await db.insert(organization_settings).values({
      organization_id: "ORG-001",
      organization_name: "Membership Business Network",
      organization_code: "MBN",
      logo_url: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&auto=format&fit=crop&q=80",
      email: "secretariat@membershipbusinessnetwork.org",
      phone: "+91 98204 88200",
      website: "https://membershipbusinessnetwork.org",
      address: "24th Floor, Platinum Corporate Towers, BKC",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      postal_code: "400051",
      timezone: "Asia/Kolkata",
      currency: "INR",
      gas_web_app_url: "https://script.google.com/macros/s/AKfycbz_MBN_EXEC_DEPLOYMENT_ID/exec",
      google_drive_folder_id: "1aB2c3D4e5F6_MBN_DRIVE_ROOT_FOLDER",
      status: "Active",
    });

    // 2. Chapters (Lakshya & Unnati initial + support for more)
    await db.insert(chapters).values([
      {
        chapter_id: "CHAP-001",
        chapter_name: "Lakshya",
        chapter_code: "LAK",
        chapter_leader_member_id: "MEM-2026-001",
        meeting_day: "Wednesday",
        meeting_time: "07:30 AM - 09:30 AM",
        meeting_mode: "In-Person",
        meeting_location: "Taj Lands End, Bandra West, Mumbai",
        city: "Mumbai",
        member_target: 50,
        current_member_count: 9,
        status: "Active",
      },
      {
        chapter_id: "CHAP-002",
        chapter_name: "Unnati",
        chapter_code: "UNN",
        chapter_leader_member_id: "MEM-2026-008",
        meeting_day: "Friday",
        meeting_time: "07:30 AM - 09:30 AM",
        meeting_mode: "In-Person",
        meeting_location: "Trident Hotel, Nariman Point, Mumbai",
        city: "Mumbai",
        member_target: 45,
        current_member_count: 7,
        status: "Active",
      },
    ]);

    // 3. Exact 10 Categories required in spec
    await db.insert(categories).values([
      {
        category_id: "CAT-001",
        category_name: "Trading",
        category_code: "TRD",
        description: "Industrial & Commodity Trading House",
        max_members_allowed: 2,
        active_member_count: 2,
        status: "Active",
        sort_order: 1,
      },
      {
        category_id: "CAT-002",
        category_name: "Accounting",
        category_code: "ACC",
        description: "Corporate & SME Accounting Practice",
        max_members_allowed: 2,
        active_member_count: 1,
        status: "Active",
        sort_order: 2,
      },
      {
        category_id: "CAT-003",
        category_name: "Architect",
        category_code: "ARC",
        description: "Commercial & Residential Principal Architect",
        max_members_allowed: 2,
        active_member_count: 2,
        status: "Active",
        sort_order: 3,
      },
      {
        category_id: "CAT-004",
        category_name: "Architecture and Interior Designing",
        category_code: "AID",
        description: "Turnkey Interior Design & Luxury Studio",
        max_members_allowed: 2,
        active_member_count: 2,
        status: "Active",
        sort_order: 4,
      },
      {
        category_id: "CAT-005",
        category_name: "CA - Accounting",
        category_code: "CAA",
        description: "Chartered Accountant Statutory Audit & Financials",
        max_members_allowed: 2,
        active_member_count: 1,
        status: "Active",
        sort_order: 5,
      },
      {
        category_id: "CAT-006",
        category_name: "Registrations and Compliance",
        category_code: "REG",
        description: "ROC, FSSAI, Startup India & Corporate Compliance",
        max_members_allowed: 2,
        active_member_count: 2,
        status: "Active",
        sort_order: 6,
      },
      {
        category_id: "CAT-007",
        category_name: "CA - Direct and Indirect Taxes",
        category_code: "CAT",
        description: "GST Litigation, Income Tax Advisory & Appeals",
        max_members_allowed: 1,
        active_member_count: 1,
        status: "Active",
        sort_order: 7,
      },
      {
        category_id: "CAT-008",
        category_name: "Career Counselling & Abroad Study Consultant",
        category_code: "EDU",
        description: "Ivy League & UK/Europe Higher Education Advisory",
        max_members_allowed: 2,
        active_member_count: 1,
        status: "Active",
        sort_order: 8,
      },
      {
        category_id: "CAT-009",
        category_name: "CEO/CFO Services",
        category_code: "CFO",
        description: "Virtual CFO, Fundraising & Capital Advisory",
        max_members_allowed: 2,
        active_member_count: 2,
        status: "Active",
        sort_order: 9,
      },
      {
        category_id: "CAT-010",
        category_name: "Clinical Dietician",
        category_code: "NUT",
        description: "Metabolic Health & Executive Nutrition Coach",
        max_members_allowed: 2,
        active_member_count: 0,
        status: "Active",
        sort_order: 10,
      },
    ]);

    // 4. Members (14 Approved Active + 2 Pending Approval applications)
    const seedMembers = [
      {
        member_id: "MEM-2026-001",
        membership_no: "MBN-LAK-001",
        first_name: "Vikram",
        middle_name: "R.",
        last_name: "Singhania",
        full_name: "Vikram R. Singhania",
        profile_photo_url:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        email: "vikram@apexcapitalcfo.in",
        mobile: "+91 98201 11234",
        whatsapp_no: "+91 98201 11234",
        gender: "Male",
        date_of_birth: "1982-05-14",
        business_name: "Apex Virtual CFO Partners",
        designation: "Managing Partner",
        business_description:
          "Fractional CFO & Private Equity Fund Structuring for Mid-Market Enterprises",
        business_address: "1204 Maker Chambers IV, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://apexcapitalcfo.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-009",
        referral_member_id: "MEM-2026-002",
        joining_date: "2024-01-10",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Premium Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-01-10 10:00:00",
        notes: "Chapter President - Lakshya Chapter",
      },
      {
        member_id: "MEM-2026-002",
        membership_no: "MBN-LAK-002",
        first_name: "Ananya",
        middle_name: "",
        last_name: "Mehta",
        full_name: "Ananya Mehta",
        profile_photo_url:
          "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
        email: "ananya@studiomehta.com",
        mobile: "+91 98202 34567",
        whatsapp_no: "+91 98202 34567",
        gender: "Female",
        date_of_birth: "1987-09-22",
        business_name: "Studio Mehta Architecture",
        designation: "Principal Architect",
        business_description:
          "Sustainable Commercial LEED-Certified Buildings & Luxury Villas",
        business_address: "4th Floor, Pali Hill Studios, Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400050",
        website: "https://studiomehta.com",
        chapter_id: "CHAP-001",
        category_id: "CAT-003",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-02-15",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-02-15 11:30:00",
        notes: "Top referral giver Q1 2026",
      },
      {
        member_id: "MEM-2026-003",
        membership_no: "MBN-LAK-003",
        first_name: "CA Rajesh",
        middle_name: "K.",
        last_name: "Kothari",
        full_name: "CA Rajesh K. Kothari",
        profile_photo_url:
          "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
        email: "rajesh@kothariandco.in",
        mobile: "+91 98210 67890",
        whatsapp_no: "+91 98210 67890",
        gender: "Male",
        date_of_birth: "1979-11-03",
        business_name: "Kothari & Associates LLP",
        designation: "Senior Partner - Direct & Indirect Tax",
        business_description:
          "International Taxation, Transfer Pricing & GST Appellate Practice",
        business_address: "702 Fort House, DN Road, Fort",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400001",
        website: "https://kothariandco.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-007",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-03-01",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Corporate Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-03-01 09:00:00",
        notes: "Membership Committee Chair",
      },
      {
        member_id: "MEM-2026-004",
        membership_no: "MBN-LAK-004",
        first_name: "Neha",
        middle_name: "",
        last_name: "Deshmukh",
        full_name: "Neha Deshmukh",
        profile_photo_url:
          "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80",
        email: "neha@compliancevault.co.in",
        mobile: "+91 99201 44551",
        whatsapp_no: "+91 99201 44551",
        gender: "Female",
        date_of_birth: "1989-03-17",
        business_name: "Compliance Vault India",
        designation: "Founder & CS",
        business_description:
          "Turnkey Corporate Registrations, FDI Compliance & SEBI Filings",
        business_address: "305 Kanakia Wall Street, Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400093",
        website: "https://compliancevault.co.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-006",
        referral_member_id: "MEM-2026-003",
        joining_date: "2024-04-12",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-04-12 12:00:00",
        notes: "Visitor Host Coordinator",
      },
      {
        member_id: "MEM-2026-005",
        membership_no: "MBN-LAK-005",
        first_name: "Arjun",
        middle_name: "S.",
        last_name: "Kapoor",
        full_name: "Arjun S. Kapoor",
        profile_photo_url:
          "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80",
        email: "arjun@globaltradehub.in",
        mobile: "+91 98205 99881",
        whatsapp_no: "+91 98205 99881",
        gender: "Male",
        date_of_birth: "1984-08-09",
        business_name: "Global Steel & Specialty Alloys",
        designation: "Director - International Trading",
        business_description:
          "Bulk Import & Export of Structural Steel & Specialty Industrial Alloys",
        business_address: "512 Tulsiani Chambers, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://globaltradehub.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-001",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-05-20",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Corporate Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-05-20 14:15:00",
        notes: "Highest single referral closed value ₹45 Lakhs",
      },
      {
        member_id: "MEM-2026-006",
        membership_no: "MBN-LAK-006",
        first_name: "Pooja",
        middle_name: "",
        last_name: "Chopra",
        full_name: "Pooja Chopra",
        profile_photo_url:
          "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80",
        email: "pooja@luxeinteriors.co.in",
        mobile: "+91 98199 12389",
        whatsapp_no: "+91 98199 12389",
        gender: "Female",
        date_of_birth: "1991-01-25",
        business_name: "Luxe Atelier Interiors",
        designation: "Creative Director",
        business_description:
          "Penthouse & High-End Office Spatial Architecture & Italian Furniture",
        business_address: "18 Worli Sea Face Plaza, Worli",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400030",
        website: "https://luxeinteriors.co.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-004",
        referral_member_id: "MEM-2026-002",
        joining_date: "2024-06-11",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-06-11 16:00:00",
        notes: "100% Meeting attendance streak",
      },
      {
        member_id: "MEM-2026-007",
        membership_no: "MBN-LAK-007",
        first_name: "Dr. Mihir",
        middle_name: "",
        last_name: "Shah",
        full_name: "Dr. Mihir Shah",
        profile_photo_url:
          "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        email: "mihir@globaledupath.com",
        mobile: "+91 98207 43100",
        whatsapp_no: "+91 98207 43100",
        gender: "Male",
        date_of_birth: "1980-04-10",
        business_name: "Global EduPath Overseas Advisory",
        designation: "Chief Education Advisor",
        business_description:
          "US Ivy League MBA & STEM Masters Study Abroad & Visa Consulting",
        business_address: "801 Hubtown Solaris, Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400069",
        website: "https://globaledupath.com",
        chapter_id: "CHAP-001",
        category_id: "CAT-008",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-07-05",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-07-05 10:20:00",
        notes: "Education & Mentorship Lead",
      },
      // UNNATI CHAPTER MEMBERS
      {
        member_id: "MEM-2026-008",
        membership_no: "MBN-UNN-001",
        first_name: "Siddharth",
        middle_name: "V.",
        last_name: "Oberoi",
        full_name: "Siddharth V. Oberoi",
        profile_photo_url:
          "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
        email: "siddharth@oberoiventures.in",
        mobile: "+91 98211 77665",
        whatsapp_no: "+91 98211 77665",
        gender: "Male",
        date_of_birth: "1978-12-01",
        business_name: "Oberoi Capital & Growth Partners",
        designation: "Executive Director",
        business_description:
          "Debt Syndication, M&A Advisory & Working Capital Finance for Growth Companies",
        business_address: "15th Floor, Express Towers, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://oberoiventures.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-009",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-01-15",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Premium Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-01-15 09:30:00",
        notes: "Chapter President - Unnati Chapter",
      },
      {
        member_id: "MEM-2026-009",
        membership_no: "MBN-UNN-002",
        first_name: "Kavita",
        middle_name: "",
        last_name: "Nair",
        full_name: "Kavita Nair",
        profile_photo_url:
          "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&auto=format&fit=crop&q=80",
        email: "kavita@nairarchitects.in",
        mobile: "+91 98208 65432",
        whatsapp_no: "+91 98208 65432",
        gender: "Female",
        date_of_birth: "1985-06-18",
        business_name: "Kavita Nair Architectural Guild",
        designation: "Founder & Lead Architect",
        business_description:
          "Corporate Experience Centers, Hospitality & Green Building Architecture",
        business_address: "501 Peninsula Corporate Park, Lower Parel",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400013",
        website: "https://nairarchitects.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-003",
        referral_member_id: "MEM-2026-008",
        joining_date: "2024-02-20",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-02-20 11:00:00",
        notes: "Vice President - Unnati Chapter",
      },
      {
        member_id: "MEM-2026-010",
        membership_no: "MBN-UNN-003",
        first_name: "CA Suman",
        middle_name: "",
        last_name: "Bhattacharya",
        full_name: "CA Suman Bhattacharya",
        profile_photo_url:
          "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80",
        email: "suman@bhattacharyaca.com",
        mobile: "+91 98212 90123",
        whatsapp_no: "+91 98212 90123",
        gender: "Male",
        date_of_birth: "1983-10-12",
        business_name: "Bhattacharya & Co. Chartered Accountants",
        designation: "Partner - Assurance & IndAS",
        business_description:
          "Statutory Audit, IPO Readiness & Internal Financial Controls",
        business_address: "404 Raheja Chambers, Free Press Journal Marg",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://bhattacharyaca.com",
        chapter_id: "CHAP-002",
        category_id: "CAT-005",
        referral_member_id: "MEM-2026-008",
        joining_date: "2024-03-10",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-03-10 15:30:00",
        notes: "Secretary/Treasurer - Unnati Chapter",
      },
      {
        member_id: "MEM-2026-011",
        membership_no: "MBN-UNN-004",
        first_name: "Rohan",
        middle_name: "",
        last_name: "Patel",
        full_name: "Rohan Patel",
        profile_photo_url:
          "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
        email: "rohan@pristinepolymers.in",
        mobile: "+91 98190 23411",
        whatsapp_no: "+91 98190 23411",
        gender: "Male",
        date_of_birth: "1986-07-29",
        business_name: "Pristine Petrochemicals & Polymers",
        designation: "Managing Director",
        business_description:
          "Pan-India Trading of Specialty Industrial Granules & Packaging Resins",
        business_address: "210 Vashi Infotech Park, Navi Mumbai",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400703",
        website: "https://pristinepolymers.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-001",
        referral_member_id: "MEM-2026-008",
        joining_date: "2024-04-18",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Corporate Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-04-18 10:00:00",
        notes: "Export excellence awardee",
      },
      {
        member_id: "MEM-2026-012",
        membership_no: "MBN-UNN-005",
        first_name: "Shruti",
        middle_name: "",
        last_name: "Malhotra",
        full_name: "Shruti Malhotra",
        profile_photo_url:
          "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80",
        email: "shruti@urbancontour.co.in",
        mobile: "+91 98209 87654",
        whatsapp_no: "+91 98209 87654",
        gender: "Female",
        date_of_birth: "1990-11-05",
        business_name: "Urban Contour Interiors",
        designation: "Founder",
        business_description:
          "Bespoke Commercial Spaces, Flagship Retail Stores & Luxury Showrooms",
        business_address: "902 Raghuvanshi Mills Compound, Lower Parel",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400013",
        website: "https://urbancontour.co.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-004",
        referral_member_id: "MEM-2026-009",
        joining_date: "2024-05-15",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-05-15 14:00:00",
        notes: "Active contributor to social posts",
      },
      {
        member_id: "MEM-2026-013",
        membership_no: "MBN-UNN-006",
        first_name: "Adv. Pranav",
        middle_name: "",
        last_name: "Joshi",
        full_name: "Adv. Pranav Joshi",
        profile_photo_url:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        email: "pranav@joshilegalcompliance.in",
        mobile: "+91 98203 55667",
        whatsapp_no: "+91 98203 55667",
        gender: "Male",
        date_of_birth: "1981-02-14",
        business_name: "Joshi Corporate Legal & IP Compliance",
        designation: "Senior Legal Counsel",
        business_description:
          "Trademark Filing, NCLT Mergers, Commercial Contracts & ROC Secretarial",
        business_address: "601 Mittal Court B-Wing, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://joshilegalcompliance.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-006",
        referral_member_id: "MEM-2026-010",
        joining_date: "2024-06-25",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-06-25 17:00:00",
        notes: "Mentor for new inductees",
      },
      {
        member_id: "MEM-2026-014",
        membership_no: "MBN-LAK-008",
        first_name: "Devanshu",
        middle_name: "",
        last_name: "Kulkarni",
        full_name: "Devanshu Kulkarni",
        profile_photo_url:
          "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80",
        email: "devanshu@ledgerbooks.in",
        mobile: "+91 98206 44332",
        whatsapp_no: "+91 98206 44332",
        gender: "Male",
        date_of_birth: "1988-09-09",
        business_name: "LedgerBooks Outsourced Accounting",
        designation: "Founder & CEO",
        business_description:
          "Cloud ERP Bookkeeping, Payroll & MIS Automation for Tech Startups",
        business_address: "411 WeWork Enam Sambhav, BKC",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400051",
        website: "https://ledgerbooks.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-002",
        referral_member_id: "MEM-2026-001",
        joining_date: "2024-08-01",
        membership_start_date: "2026-01-01",
        membership_end_date: "2026-12-31",
        membership_type: "Standard Membership",
        membership_status: "Active",
        approval_status: "Approved",
        approved_by: "Super Admin",
        approved_at: "2024-08-01 11:00:00",
        notes: "Active referral partner",
      },
      // PENDING APPROVAL APPLICATIONS (so administrators can test 1-click Approve / Reject)
      {
        member_id: "MEM-2026-015",
        membership_no: "APP-LAK-2026-01",
        first_name: "Dt. Ritu",
        middle_name: "",
        last_name: "Sengupta",
        full_name: "Dt. Ritu Sengupta",
        profile_photo_url:
          "https://images.unsplash.com/photo-1594744803329-e58b31de7bf5?w=200&auto=format&fit=crop&q=80",
        email: "ritu@nutriwellclinic.in",
        mobile: "+91 98204 19901",
        whatsapp_no: "+91 98204 19901",
        gender: "Female",
        date_of_birth: "1992-05-11",
        business_name: "NutriWell Executive Metabolic Clinic",
        designation: "Chief Clinical Dietician",
        business_description:
          "Gut Longevity, Reversal of Metabolic Syndrome & C-Suite Performance Dietetics",
        business_address: "12 Linking Road Medical Centre, Khar West",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400052",
        website: "https://nutriwellclinic.in",
        chapter_id: "CHAP-001",
        category_id: "CAT-010",
        referral_member_id: "MEM-2026-002",
        joining_date: "2026-03-25",
        membership_start_date: "2026-04-01",
        membership_end_date: "2027-03-31",
        membership_type: "Standard Membership",
        membership_status: "Pending",
        approval_status: "Pending",
        approved_by: null,
        approved_at: null,
        notes: "Visitor converted from March 20 Weekly Breakfast Meeting",
      },
      {
        member_id: "MEM-2026-016",
        membership_no: "APP-UNN-2026-02",
        first_name: "Harsh",
        middle_name: "",
        last_name: "Vardhan",
        full_name: "Harsh Vardhan",
        profile_photo_url:
          "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
        email: "harsh@eduglobalpartners.in",
        mobile: "+91 98218 89900",
        whatsapp_no: "+91 98218 89900",
        gender: "Male",
        date_of_birth: "1987-12-08",
        business_name: "EduGlobal Career Pathways",
        designation: "Director",
        business_description:
          "Overseas Higher Education Advisory & Medical University Admissions",
        business_address: "704 Dalamal Tower, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postal_code: "400021",
        website: "https://eduglobalpartners.in",
        chapter_id: "CHAP-002",
        category_id: "CAT-008",
        referral_member_id: "MEM-2026-008",
        joining_date: "2026-03-28",
        membership_start_date: "2026-04-01",
        membership_end_date: "2027-03-31",
        membership_type: "Standard Membership",
        membership_status: "Pending",
        approval_status: "Pending",
        approved_by: null,
        approved_at: null,
        notes: "Referred by Siddharth Oberoi after visitor interview",
      },
    ];

    await db.insert(members).values(seedMembers);

    // 5. Users (Role-based access system)
    await db.insert(users).values([
      {
        user_id: "USR-SUPER-01",
        member_id: "MEM-2026-001",
        full_name: "Vikram R. Singhania (Super Admin)",
        email: "vikram@apexcapitalcfo.in",
        mobile: "+91 98201 11234",
        auth_uid: "firebase_super_admin_uid_001",
        role: "Super Admin",
        status: "Active",
      },
      {
        user_id: "USR-ORG-02",
        member_id: null,
        full_name: "Secretariat HQ (Organization Admin)",
        email: "secretariat@membershipbusinessnetwork.org",
        mobile: "+91 98204 88200",
        auth_uid: "firebase_org_admin_uid_002",
        role: "Organization Admin",
        status: "Active",
      },
      {
        user_id: "USR-CHAP-LAK",
        member_id: "MEM-2026-002",
        full_name: "Ananya Mehta (Chapter Admin - Lakshya)",
        email: "ananya@studiomehta.com",
        mobile: "+91 98202 34567",
        auth_uid: "firebase_chap_admin_lak_003",
        role: "Chapter Admin",
        status: "Active",
      },
      {
        user_id: "USR-CHAP-UNN",
        member_id: "MEM-2026-008",
        full_name: "Siddharth V. Oberoi (Chapter Admin - Unnati)",
        email: "siddharth@oberoiventures.in",
        mobile: "+91 98211 77665",
        auth_uid: "firebase_chap_admin_unn_004",
        role: "Chapter Admin",
        status: "Active",
      },
      {
        user_id: "USR-MEMBER-05",
        member_id: "MEM-2026-003",
        full_name: "CA Rajesh K. Kothari (Member)",
        email: "rajesh@kothariandco.in",
        mobile: "+91 98210 67890",
        auth_uid: "firebase_member_uid_005",
        role: "Member",
        status: "Active",
      },
      {
        user_id: "USR-STAFF-06",
        member_id: null,
        full_name: "Sneha G. (Operations Staff)",
        email: "sneha.staff@membershipbusinessnetwork.org",
        mobile: "+91 98199 00112",
        auth_uid: "firebase_staff_uid_006",
        role: "Staff",
        status: "Active",
      },
      {
        user_id: "USR-VIEWER-07",
        member_id: null,
        full_name: "Advisory Board Auditor (Viewer)",
        email: "auditor@membershipbusinessnetwork.org",
        mobile: "+91 98200 00000",
        auth_uid: "firebase_viewer_uid_007",
        role: "Viewer",
        status: "Active",
      },
    ]);

    // 6. Community Social Posts (stored in Google Drive folder simulator URLs)
    await db.insert(posts).values([
      {
        post_id: "PST-001",
        member_id: "MEM-2026-001",
        post_type: "Referral Success",
        title: "🎉 ₹45 Lakh Private Equity Advisory Closed via Lakshya Chapter Referral!",
        content:
          "Huge shoutout to Ananya Mehta (Studio Mehta Architecture) for introducing us to a leading luxury real estate developer. After 3 months of diligence, we closed their virtual CFO and debt structuring mandate today! Thank You For Closed Business (TYFCB) slip submitted.",
        media_type: "image",
        media_url:
          "https://images.unsplash.com/photo-1552581234-26160f608093?w=800&auto=format&fit=crop&q=80",
        visibility: "All Members",
        status: "Published",
        is_pinned: true,
      },
      {
        post_id: "PST-002",
        member_id: "MEM-2026-008",
        post_type: "Event Update",
        title: "Unnati Chapter Cross-Chapter Speed Networking Meetup This Friday",
        content:
          "We are welcoming 12 special business visitors from pharmaceuticals and logistics sectors this Friday at Trident Nariman Point. Remember to bring at least 30 business cards and prepare your 45-second elevator pitch!",
        media_type: "image",
        media_url:
          "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80",
        visibility: "All Members",
        status: "Published",
        is_pinned: true,
      },
      {
        post_id: "PST-003",
        member_id: "MEM-2026-002",
        post_type: "Business Update",
        title: "LEED Platinum Commercial Project Handover in Worli",
        content:
          "Delighted to share our latest 42,000 sq ft headquarters completion for an international fintech firm. Special thanks to Pooja Chopra (Luxe Atelier) for executive boardroom interior accents!",
        media_type: "image",
        media_url:
          "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
        visibility: "All Members",
        status: "Published",
        is_pinned: false,
      },
      {
        post_id: "PST-004",
        member_id: "MEM-2026-003",
        post_type: "Document",
        title: "FY 2026-27 Union Budget Direct Tax & MSME Compliance Cheat-Sheet",
        content:
          "Uploaded our firm's comprehensive 12-page executive summary PDF on 43B(h) payment timelines and GST input credit rules. Available in the Google Drive Membership Network / Documents folder.",
        media_type: "document",
        media_url:
          "https://drive.google.com/file/d/1MBN_TAX_CHEATSHEET_2026_PDF/view",
        visibility: "All Members",
        status: "Published",
        is_pinned: false,
      },
      {
        post_id: "PST-005",
        member_id: "MEM-2026-005",
        post_type: "Text",
        title: "Looking for Tier-1 Warehousing & Cold Chain Partners in Gujarat",
        content:
          "One of our European industrial steel buyers is expanding operations in Sanand/Mundra. If any member has strong connections with warehouse developers or customs clearing agents, let's connect after Wednesday's meeting!",
        media_type: null,
        media_url: null,
        visibility: "All Members",
        status: "Published",
        is_pinned: false,
      },
      {
        post_id: "PST-006",
        member_id: "MEM-2026-006",
        post_type: "Training Update",
        title: "Key Takeaways from Leadership Presentation Mastery Workshop",
        content:
          "Practicing the 'Specific Ask' framework changed how I pitch commercial interior contracts. Instead of asking for 'anyone buying office furniture', I asked for 'CFOs leasing 15,000+ sq ft in BKC' and received 2 warm intros within 48 hours!",
        media_type: null,
        media_url: null,
        visibility: "All Members",
        status: "Published",
        is_pinned: false,
      },
    ]);

    // 7. Post Comments & Likes
    await db.insert(post_comments).values([
      {
        comment_id: "CMT-001",
        post_id: "PST-001",
        member_id: "MEM-2026-002",
        comment_text:
          "Congratulations Vikram! The client loved your 13-week cash flow modeling presentation.",
      },
      {
        comment_id: "CMT-002",
        post_id: "PST-001",
        member_id: "MEM-2026-003",
        comment_text: "True power of structured B2B referrals! Inspiring TYFCB slip.",
      },
      {
        comment_id: "CMT-003",
        post_id: "PST-005",
        member_id: "MEM-2026-011",
        comment_text:
          "Arjun, I have 2 direct logistics contacts operating 1.5 Lakh sq ft in Mundra. Passing a referral slip right now!",
      },
    ]);

    await db.insert(post_likes).values([
      { like_id: "LIK-001", post_id: "PST-001", member_id: "MEM-2026-002", reaction_type: "Celebrate" },
      { like_id: "LIK-002", post_id: "PST-001", member_id: "MEM-2026-003", reaction_type: "Celebrate" },
      { like_id: "LIK-003", post_id: "PST-001", member_id: "MEM-2026-004", reaction_type: "Like" },
      { like_id: "LIK-004", post_id: "PST-001", member_id: "MEM-2026-008", reaction_type: "Support" },
      { like_id: "LIK-005", post_id: "PST-002", member_id: "MEM-2026-001", reaction_type: "Interested" },
      { like_id: "LIK-006", post_id: "PST-003", member_id: "MEM-2026-006", reaction_type: "Celebrate" },
    ]);

    // 8. Admin Announcements
    await db.insert(announcements).values([
      {
        announcement_id: "ANN-001",
        title: "Q2 2026 Chapter Leadership Awards & Grand Visitors Day Gala",
        message:
          "All members of Lakshya and Unnati chapters are invited to the Q2 Networking Leadership Gala on April 18, 2026 at St. Regis Mumbai. Bring 2 prospective C-suite business visitors per member.",
        image_url:
          "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&auto=format&fit=crop&q=80",
        attachment_url:
          "https://drive.google.com/file/d/1MBN_GALA_INVITE_BROCHURE_PDF/view",
        target_type: "All Members",
        priority: "Urgent",
        publish_date: "2026-03-20",
        expiry_date: "2026-04-20",
        status: "Published",
        created_by: "Super Admin",
      },
      {
        announcement_id: "ANN-002",
        title: "Category Protection Enforcement & Attendance Benchmark Policy",
        message:
          "Reminder: Each business category permits a maximum capacity as configured in Categories Settings. Members with attendance dropping below 75% will be placed on review status.",
        target_type: "All Members",
        priority: "High",
        publish_date: "2026-03-10",
        expiry_date: "2026-06-30",
        status: "Published",
        created_by: "Organization Admin",
      },
    ]);

    // 9. Events & Meetings
    await db.insert(events).values([
      {
        event_id: "EVT-001",
        chapter_id: "CHAP-001",
        event_name: "Lakshya Weekly Executive Networking Breakfast",
        event_type: "Weekly Meeting",
        description:
          "Structured 20-item agenda meeting including Feature Presentation by CA Rajesh Kothari and One-to-One networking breakouts.",
        event_date: "2026-04-01",
        start_time: "07:30 AM",
        end_time: "09:30 AM",
        event_mode: "In-Person",
        venue_name: "Taj Lands End, Bandra West",
        venue_address: "Bandstand Promenade, Bandra West, Mumbai",
        capacity: 65,
        registration_required: true,
        registration_deadline: "2026-03-31",
        event_status: "Scheduled",
        created_by: "Chapter Admin",
      },
      {
        event_id: "EVT-002",
        chapter_id: "CHAP-002",
        event_name: "Unnati Chapter Friday Power Breakfast & Visitor Day",
        event_type: "Weekly Meeting",
        description:
          "High-energy referral exchange meeting featuring 60-second member introductions and guest speaker from Bombay Chamber of Commerce.",
        event_date: "2026-04-03",
        start_time: "07:30 AM",
        end_time: "09:30 AM",
        event_mode: "In-Person",
        venue_name: "Trident Hotel, Nariman Point",
        venue_address: "CR2 Marine Drive, Nariman Point, Mumbai",
        capacity: 60,
        registration_required: true,
        registration_deadline: "2026-04-02",
        event_status: "Scheduled",
        created_by: "Chapter Admin",
      },
      {
        event_id: "EVT-003",
        chapter_id: "ALL",
        event_name: "Inter-Chapter Joint Business Conclave & Speed Networking",
        event_type: "Networking Event",
        description:
          "Joint networking summit for Lakshya and Unnati members with curated B2B matchmaking tables.",
        event_date: "2026-04-18",
        start_time: "05:00 PM",
        end_time: "09:00 PM",
        event_mode: "In-Person",
        venue_name: "The St. Regis Mumbai, Lower Parel",
        venue_address: "462 Senapati Bapat Marg, Lower Parel, Mumbai",
        capacity: 150,
        registration_required: true,
        registration_deadline: "2026-04-15",
        event_status: "Scheduled",
        created_by: "Organization Admin",
      },
      {
        event_id: "EVT-004",
        chapter_id: "CHAP-001",
        event_name: "Completed Lakshya Weekly Breakfast (March 25)",
        event_type: "Weekly Meeting",
        description: "Completed weekly chapter meeting with 94% attendance rate.",
        event_date: "2026-03-25",
        start_time: "07:30 AM",
        end_time: "09:30 AM",
        event_mode: "In-Person",
        venue_name: "Taj Lands End, Bandra West",
        venue_address: "Bandstand Promenade, Bandra West, Mumbai",
        capacity: 65,
        registration_required: true,
        event_status: "Completed",
        created_by: "Chapter Admin",
      },
    ]);

    // 10. Event Attendance Records
    await db.insert(event_attendance).values([
      {
        attendance_id: "ATT-001",
        event_id: "EVT-004",
        member_id: "MEM-2026-001",
        attendance_status: "Present",
        check_in_time: "07:15 AM",
        guest_count: 1,
      },
      {
        attendance_id: "ATT-002",
        event_id: "EVT-004",
        member_id: "MEM-2026-002",
        attendance_status: "Present",
        check_in_time: "07:22 AM",
        guest_count: 2,
      },
      {
        attendance_id: "ATT-003",
        event_id: "EVT-004",
        member_id: "MEM-2026-003",
        attendance_status: "Present",
        check_in_time: "07:28 AM",
        guest_count: 0,
      },
      {
        attendance_id: "ATT-004",
        event_id: "EVT-004",
        member_id: "MEM-2026-004",
        attendance_status: "Late",
        check_in_time: "07:39 AM",
        guest_count: 0,
      },
      {
        attendance_id: "ATT-005",
        event_id: "EVT-004",
        member_id: "MEM-2026-005",
        attendance_status: "Present",
        check_in_time: "07:20 AM",
        guest_count: 1,
      },
      {
        attendance_id: "ATT-006",
        event_id: "EVT-004",
        member_id: "MEM-2026-006",
        attendance_status: "Present",
        check_in_time: "07:18 AM",
        guest_count: 0,
      },
      {
        attendance_id: "ATT-007",
        event_id: "EVT-004",
        member_id: "MEM-2026-007",
        attendance_status: "Excused",
        remarks: "Traveling to London education fair",
      },
    ]);

    // 11. Visitors (Visitor pipeline: Invited → Registered → Attended → Follow-up Required → Converted)
    await db.insert(visitors).values([
      {
        visitor_id: "VIS-001",
        chapter_id: "CHAP-001",
        event_id: "EVT-001",
        referred_by_member_id: "MEM-2026-001",
        visitor_name: "Nikhil Godbole",
        business_name: "Godbole Solar & CleanTech EPC",
        category_interest: "CAT-001",
        mobile: "+91 98200 77112",
        email: "nikhil@godbolesolar.in",
        city: "Mumbai",
        visit_date: "2026-04-01",
        visit_status: "Registered",
        notes: "Interested in 5MW solar rooftop projects for industrial members",
      },
      {
        visitor_id: "VIS-002",
        chapter_id: "CHAP-001",
        event_id: "EVT-004",
        referred_by_member_id: "MEM-2026-002",
        visitor_name: "Dt. Ritu Sengupta",
        business_name: "NutriWell Executive Metabolic Clinic",
        category_interest: "CAT-010",
        mobile: "+91 98204 19901",
        email: "ritu@nutriwellclinic.in",
        city: "Mumbai",
        visit_date: "2026-03-25",
        visit_status: "Converted",
        converted_member_id: "MEM-2026-015",
        notes: "Application submitted for Clinical Dietician seat (CAT-010)",
      },
      {
        visitor_id: "VIS-003",
        chapter_id: "CHAP-002",
        event_id: "EVT-002",
        referred_by_member_id: "MEM-2026-008",
        visitor_name: "Sameer Wadhwa",
        business_name: "Wadhwa CyberSec Advisory",
        category_interest: "CAT-006",
        mobile: "+91 98209 11990",
        email: "sameer@wadhwacyber.com",
        city: "Mumbai",
        visit_date: "2026-04-03",
        visit_status: "Attended",
        notes: "Follow-up required by Membership Committee on ISO 27001 audit seat",
      },
      {
        visitor_id: "VIS-004",
        chapter_id: "CHAP-002",
        event_id: "EVT-002",
        referred_by_member_id: "MEM-2026-009",
        visitor_name: "Meera Krishnan",
        business_name: "Krishnan PR & Corporate Media",
        category_interest: "CAT-008",
        mobile: "+91 98198 77661",
        email: "meera@krishnanpr.in",
        city: "Mumbai",
        visit_date: "2026-03-21",
        visit_status: "Follow-up Required",
        notes: "Very positive feedback from chapter members",
      },
      {
        visitor_id: "VIS-005",
        chapter_id: "CHAP-001",
        event_id: "EVT-001",
        referred_by_member_id: "MEM-2026-005",
        visitor_name: "Tarun Bhardwaj",
        business_name: "Bhardwaj Packaging Machinery",
        category_interest: "CAT-001",
        mobile: "+91 99203 99001",
        email: "tarun@bhardwajpack.in",
        city: "Mumbai",
        visit_date: "2026-04-01",
        visit_status: "Invited",
        notes: "Confirmed guest invitation for next Wednesday",
      },
    ]);

    // 12. Referrals across all 5 statuses: New → Contacted → In Progress → Converted → Closed
    await db.insert(referrals).values([
      {
        referral_id: "REF-001",
        chapter_id: "CHAP-001",
        given_by_member_id: "MEM-2026-002", // Ananya Mehta
        received_by_member_id: "MEM-2026-001", // Vikram Singhania
        client_name: "Aakash Piramal",
        client_company: "Piramal Horizon Estates Pvt Ltd",
        client_mobile: "+91 98200 11999",
        client_email: "aakash@piramalhorizon.com",
        referral_category_id: "CAT-009",
        referral_description:
          "CFO Mandate & ₹45 Cr Debt Structuring for Commercial Tower in BKC",
        referral_date: "2026-02-10",
        referral_status: "Closed",
        estimated_business_value: "4500000",
        closed_business_value: "4500000",
        currency: "INR",
        closure_date: "2026-03-24",
        notes: "Contract signed and retainer billed! TYFCB transaction recorded.",
      },
      {
        referral_id: "REF-002",
        chapter_id: "CHAP-001",
        given_by_member_id: "MEM-2026-001", // Vikram Singhania
        received_by_member_id: "MEM-2026-003", // CA Rajesh Kothari
        client_name: "Suresh Agarwal",
        client_company: "Agarwal Precision Forgings Ltd",
        client_mobile: "+91 98210 22334",
        client_email: "suresh@agarwalforgings.in",
        referral_category_id: "CAT-007",
        referral_description:
          "Transfer Pricing Study & Appellate Tribunal Representation for FY25",
        referral_date: "2026-03-01",
        referral_status: "Closed",
        estimated_business_value: "1850000",
        closed_business_value: "1850000",
        currency: "INR",
        closure_date: "2026-03-20",
        notes: "Appeal successfully drafted and retainer paid.",
      },
      {
        referral_id: "REF-003",
        chapter_id: "CHAP-001",
        given_by_member_id: "MEM-2026-003", // CA Rajesh Kothari
        received_by_member_id: "MEM-2026-002", // Ananya Mehta
        client_name: "Deepak Chawla",
        client_company: "Chawla Wealth Management HQ",
        client_mobile: "+91 98199 44332",
        client_email: "deepak@chawlawealth.com",
        referral_category_id: "CAT-003",
        referral_description:
          "Turnkey Architecture & Interior Fitout for 8,500 sq ft Private Wealth Office",
        referral_date: "2026-03-12",
        referral_status: "In Progress",
        estimated_business_value: "3200000",
        closed_business_value: "0",
        currency: "INR",
        notes: "3D renders presented and BOQ under final client sign-off.",
      },
      {
        referral_id: "REF-004",
        chapter_id: "CHAP-001",
        given_by_member_id: "MEM-2026-005", // Arjun Kapoor
        received_by_member_id: "MEM-2026-004", // Neha Deshmukh
        client_name: "Markus Schneider",
        client_company: "EuroAlloy India Subsidiary",
        client_mobile: "+91 98205 33441",
        client_email: "markus@euroalloy.de",
        referral_category_id: "CAT-006",
        referral_description:
          "WOS Incorporation, RBI FEMA Filings & Annual ROC Secretarial Retainer",
        referral_date: "2026-03-15",
        referral_status: "Closed",
        estimated_business_value: "950000",
        closed_business_value: "950000",
        currency: "INR",
        closure_date: "2026-03-26",
        notes: "Company incorporated successfully.",
      },
      {
        referral_id: "REF-005",
        chapter_id: "CHAP-002",
        given_by_member_id: "MEM-2026-008", // Siddharth Oberoi
        received_by_member_id: "MEM-2026-011", // Rohan Patel
        client_name: "Manish Doshi",
        client_company: "Doshi Extrusions & Polymers",
        client_mobile: "+91 98211 99002",
        client_email: "manish@doshiextrusions.in",
        referral_category_id: "CAT-001",
        referral_description:
          "Annual Supply Contract for 240 MT HDPE Engineering Granules",
        referral_date: "2026-02-18",
        referral_status: "Closed",
        estimated_business_value: "4200000",
        closed_business_value: "4200000",
        currency: "INR",
        closure_date: "2026-03-18",
        notes: "First quarterly shipment delivered.",
      },
      {
        referral_id: "REF-006",
        chapter_id: "CHAP-002",
        given_by_member_id: "MEM-2026-009", // Kavita Nair
        received_by_member_id: "MEM-2026-012", // Shruti Malhotra
        client_name: "Rhea Kapoor",
        client_company: "Aura Flagship Jewellers",
        client_mobile: "+91 98207 11223",
        client_email: "rhea@aurajewels.in",
        referral_category_id: "CAT-004",
        referral_description:
          "Bespoke High-Security Luxury Showroom Interior Design in Turner Road",
        referral_date: "2026-03-19",
        referral_status: "Contacted",
        estimated_business_value: "2500000",
        closed_business_value: "0",
        currency: "INR",
        notes: "Site visit completed on Monday.",
      },
      {
        referral_id: "REF-007",
        chapter_id: "CHAP-002",
        given_by_member_id: "MEM-2026-011", // Rohan Patel
        received_by_member_id: "MEM-2026-010", // CA Suman Bhattacharya
        client_name: "Varun Goel",
        client_company: "Goel Logistics & Cold Chain Pvt Ltd",
        client_mobile: "+91 98199 77889",
        client_email: "varun@goellogistics.in",
        referral_category_id: "CAT-005",
        referral_description:
          "Statutory Audit & IndAS Transition Advisory for SME IPO Preparation",
        referral_date: "2026-03-24",
        referral_status: "New",
        estimated_business_value: "1400000",
        closed_business_value: "0",
        currency: "INR",
        notes: "Introductory phone call scheduled for Thursday.",
      },
      {
        referral_id: "REF-008",
        chapter_id: "CHAP-001",
        given_by_member_id: "MEM-2026-006", // Pooja Chopra
        received_by_member_id: "MEM-2026-007", // Dr. Mihir Shah
        client_name: "Mrs. Shalini Thapar",
        client_company: "Thapar Family Trust",
        client_mobile: "+91 98204 55661",
        client_email: "shalini@thapartrust.in",
        referral_category_id: "CAT-008",
        referral_description:
          "Ivy League MBA & Stanford Graduate Program Mentorship for Daughter",
        referral_date: "2026-02-28",
        referral_status: "Closed",
        estimated_business_value: "850000",
        closed_business_value: "850000",
        currency: "INR",
        closure_date: "2026-03-14",
        notes: "Full consulting program signed.",
      },
    ]);

    // 13. Business Transactions (Thank You For Closed Business - TYFCB)
    await db.insert(business_transactions).values([
      {
        transaction_id: "TXN-001",
        referral_id: "REF-001",
        giver_member_id: "MEM-2026-002", // Ananya Mehta gave
        receiver_member_id: "MEM-2026-001", // Vikram Singhania received business
        transaction_date: "2026-03-24",
        business_description: "Piramal Horizon Estates - Virtual CFO & Debt Mandate",
        amount: "4500000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
        remarks: "Tier 1 closed referral slip verified by Chapter Audit Committee",
      },
      {
        transaction_id: "TXN-002",
        referral_id: "REF-002",
        giver_member_id: "MEM-2026-001",
        receiver_member_id: "MEM-2026-003",
        transaction_date: "2026-03-20",
        business_description: "Agarwal Precision Forgings - International Tax & ITAT Appeal",
        amount: "1850000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-003",
        referral_id: "REF-004",
        giver_member_id: "MEM-2026-005",
        receiver_member_id: "MEM-2026-004",
        transaction_date: "2026-03-26",
        business_description: "EuroAlloy India Subsidiary WOS Incorporation & Compliance",
        amount: "950000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-004",
        referral_id: "REF-005",
        giver_member_id: "MEM-2026-008",
        receiver_member_id: "MEM-2026-011",
        transaction_date: "2026-03-18",
        business_description: "Doshi Extrusions - Annual HDPE Polymer Supply Contract Q1",
        amount: "4200000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-005",
        referral_id: "REF-008",
        giver_member_id: "MEM-2026-006",
        receiver_member_id: "MEM-2026-007",
        transaction_date: "2026-03-14",
        business_description: "Thapar Family Ivy League Advisory Program",
        amount: "850000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-006",
        referral_id: null,
        giver_member_id: "MEM-2026-003",
        receiver_member_id: "MEM-2026-014",
        transaction_date: "2026-03-10",
        business_description: "LedgerBooks Cloud Bookkeeping Retainer for Audit Clients",
        amount: "650000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-007",
        referral_id: null,
        giver_member_id: "MEM-2026-009",
        receiver_member_id: "MEM-2026-013",
        transaction_date: "2026-03-22",
        business_description: "Architectural IP & Design Copyright Registration Package",
        amount: "450000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
      {
        transaction_id: "TXN-008",
        referral_id: null,
        giver_member_id: "MEM-2026-001",
        receiver_member_id: "MEM-2026-006",
        transaction_date: "2026-02-15",
        business_description: "Apex CFO Nariman Point Executive Office Fitout",
        amount: "1400000",
        currency: "INR",
        payment_status: "Paid",
        transaction_status: "Verified",
      },
    ]);

    // 14. Membership Plans
    await db.insert(membership_plans).values([
      {
        plan_id: "PLN-001",
        plan_name: "Standard Membership",
        description: "Annual single-chapter membership with full category exclusivity",
        duration_months: 12,
        joining_fee: "7500",
        membership_fee: "38500",
        renewal_fee: "35000",
        currency: "INR",
        benefits:
          "Weekly Meeting Seat, Category Exclusivity, Regional Directory Listing, Google Drive Media Access",
        status: "Active",
      },
      {
        plan_id: "PLN-002",
        plan_name: "Premium Membership",
        description: "Executive membership with featured showcase & leadership access",
        duration_months: 12,
        joining_fee: "10000",
        membership_fee: "55000",
        renewal_fee: "48000",
        currency: "INR",
        benefits:
          "Priority Feature Presentations, Inter-Chapter Speed Networking Passes, Executive Badge",
        status: "Active",
      },
      {
        plan_id: "PLN-003",
        plan_name: "Corporate Membership",
        description: "Multi-delegate corporate nomination plan with alternate representative",
        duration_months: 12,
        joining_fee: "15000",
        membership_fee: "85000",
        renewal_fee: "75000",
        currency: "INR",
        benefits:
          "Designate 1 Primary + 1 Alternate Director, Brand Showcase across All Chapters",
        status: "Active",
      },
    ]);

    // 15. Payments
    await db.insert(payments).values([
      {
        payment_id: "PAY-001",
        member_id: "MEM-2026-001",
        plan_id: "PLN-002",
        payment_date: "2026-01-05",
        amount: "65000",
        currency: "INR",
        payment_method: "NEFT / Corporate Transfer",
        transaction_reference: "HDFC2026010599182",
        payment_status: "Paid",
        payment_for: "Renewal",
      },
      {
        payment_id: "PAY-002",
        member_id: "MEM-2026-002",
        plan_id: "PLN-001",
        payment_date: "2026-01-08",
        amount: "46000",
        currency: "INR",
        payment_method: "UPI",
        transaction_reference: "UPI600812993412",
        payment_status: "Paid",
        payment_for: "Renewal",
      },
      {
        payment_id: "PAY-003",
        member_id: "MEM-2026-015",
        plan_id: "PLN-001",
        payment_date: "2026-03-25",
        amount: "46000",
        currency: "INR",
        payment_method: "Bank Transfer",
        transaction_reference: "ICIC2026032500119",
        payment_status: "Pending",
        payment_for: "New Membership",
        remarks: "Subject to Admin Approval of Application MEM-2026-015",
      },
    ]);

    // 16. Trainings & Training Attendance
    await db.insert(trainings).values([
      {
        training_id: "TRN-001",
        chapter_id: "ALL",
        training_title: "Member Success Program (MSP) & B2B Referral Engineering",
        trainer_name: "Vikram R. Singhania",
        description:
          "Mandatory orientation on using the TYFCB pipeline, 45-second Weekly Presentations, and Google Sheets/Drive compliance.",
        training_date: "2026-04-10",
        start_time: "02:00 PM",
        end_time: "05:30 PM",
        venue_or_link: "Google Meet Live Studio + MCA Club BKC",
        training_type: "Member Success Program",
        capacity: 40,
        status: "Upcoming",
        created_by: "Super Admin",
      },
      {
        training_id: "TRN-002",
        chapter_id: "ALL",
        training_title: "Presentation Mastery: Crafting the Specific Ask",
        trainer_name: "Ananya Mehta",
        description:
          "Completed hands-on workshop on transforming generic networking requests into high-conversion executive referrals.",
        training_date: "2026-03-12",
        start_time: "03:00 PM",
        end_time: "06:00 PM",
        venue_or_link: "Taj Lands End Boardroom",
        training_type: "Presentation Mastery",
        capacity: 30,
        status: "Completed",
        created_by: "Chapter Admin",
      },
    ]);

    await db.insert(training_attendance).values([
      {
        training_attendance_id: "TRN-ATT-01",
        training_id: "TRN-002",
        member_id: "MEM-2026-006",
        attendance_status: "Present",
        certificate_url:
          "https://drive.google.com/file/d/1MBN_CERT_MEM2026006_PDF/view",
        score: 98,
        feedback: "Exceptional clarity on structuring referral asks",
      },
      {
        training_attendance_id: "TRN-ATT-02",
        training_id: "TRN-002",
        member_id: "MEM-2026-004",
        attendance_status: "Present",
        certificate_url:
          "https://drive.google.com/file/d/1MBN_CERT_MEM2026004_PDF/view",
        score: 95,
        feedback: "Generated 3 warm referrals right after training",
      },
    ]);

    // 17. Automated System Notifications
    await db.insert(notifications).values([
      {
        notification_id: "NOTIF-001",
        user_id: "ALL",
        title: "⚡ New Pending Member Application Submitted",
        message:
          "Dt. Ritu Sengupta (NutriWell Clinic) applied for Category CAT-010 (Clinical Dietician) in Lakshya Chapter. Requires Admin Approval.",
        notification_type: "Approval",
        related_module: "Members",
        related_record_id: "MEM-2026-015",
        is_read: false,
      },
      {
        notification_id: "NOTIF-002",
        user_id: "ALL",
        title: "💰 ₹45 Lakh Closed Business Transaction Recorded",
        message:
          "Vikram Singhania recorded ₹45,00,000 TYFCB thanks to referral from Ananya Mehta.",
        notification_type: "Business",
        related_module: "Referrals",
        related_record_id: "REF-001",
        is_read: false,
      },
      {
        notification_id: "NOTIF-003",
        user_id: "ALL",
        title: "📅 Reminder: Weekly Lakshya Breakfast Meeting Wednesday",
        message:
          "Please check in at Taj Lands End by 07:15 AM. 2 guest visitors confirmed.",
        notification_type: "Event",
        related_module: "Events",
        related_record_id: "EVT-001",
        is_read: false,
      },
    ]);

    // 18. Activity Log (Administrative Audit History)
    await db.insert(activity_log).values([
      {
        log_id: "LOG-2026-001",
        user_id: "Vikram R. Singhania (Super Admin)",
        action_type: "Referral Closed & TYFCB Created",
        module_name: "Referrals",
        record_id: "REF-001",
        old_data: JSON.stringify({ status: "In Progress", closed_value: 0 }),
        new_data: JSON.stringify({
          status: "Closed",
          closed_value: 4500000,
          currency: "INR",
        }),
      },
      {
        log_id: "LOG-2026-002",
        user_id: "Secretariat HQ (Organization Admin)",
        action_type: "Visitor Converted to Application",
        module_name: "Visitors",
        record_id: "VIS-002",
        old_data: JSON.stringify({ visit_status: "Attended" }),
        new_data: JSON.stringify({
          visit_status: "Converted",
          converted_member_id: "MEM-2026-015",
        }),
      },
      {
        log_id: "LOG-2026-003",
        user_id: "Ananya Mehta (Chapter Admin - Lakshya)",
        action_type: "Announcement Published",
        module_name: "Announcements",
        record_id: "ANN-001",
        old_data: null,
        new_data: JSON.stringify({
          title: "Q2 2026 Chapter Leadership Awards",
          priority: "Urgent",
        }),
      },
    ]);

    console.log("Seeding complete! 20 Google Sheet tables initialized.");
  } catch (error) {
    console.error("Seed error:", error);
  }
}
